import re
from playwright.sync_api import Page, Playwright, sync_playwright, expect


def test_all_field_present(page: Page):
    page.goto("http://localhost:3000/dashboard/employee")
    page.get_by_role("link", name="Add Closing Vouchers").click()
    page.get_by_text("Select Route").click()
    page.get_by_role("option", name="Faisalabad (New Subhan) - Lahore (Skyways-Lahore)").click()
    page.get_by_text("Select Bus Number").click()
    page.get_by_role("option", name="1658").click()
    page.locator("button").filter(has_text="Select Driver").click()
    page.get_by_role("option", name="Muhammad Imtiaz").click()
    page.locator("button").filter(has_text="Select Conductor").click()
    page.get_by_role("option", name="m A").click()
    page.get_by_placeholder("Enter Voucher Number").click()
    page.get_by_placeholder("Enter Voucher Number").fill("1234")
    page.get_by_role("button", name="Add Trip").click()
    page.get_by_role("combobox").click()
    page.get_by_role("option", name="Faisalabad (New Subhan) - Lahore (Skyways-Lahore)").click()
    page.get_by_label("Full Ticket Count").click()
    page.get_by_label("Full Ticket Count").fill("10")
    page.get_by_label("Full Ticket Count").press("Tab")
    page.get_by_placeholder("Enter half ticket count").fill("3")
    page.get_by_placeholder("Enter half ticket count").press("Tab")
    page.get_by_placeholder("Enter free ticket count").fill("2")
    page.get_by_placeholder("Enter free ticket count").press("Tab")
    page.get_by_placeholder("Enter load expense").fill("100")
    page.get_by_placeholder("Enter load expense").press("Tab")
    page.get_by_label("Reward Commission").fill("100")
    page.get_by_label("Reward Commission").press("Tab")
    page.get_by_label("Refreshment Expense").fill("100")
    page.get_by_label("Refreshment Expense").press("Tab")
    page.get_by_placeholder("Enter miscellaneous amount").fill("100")
    page.get_by_placeholder("Enter miscellaneous amount").press("Tab")
    page.get_by_placeholder("Enter checker expenses").fill("100")
    expect(page.get_by_placeholder("Actual revenue")).to_have_value("8395");
    page.get_by_placeholder("Enter explanation for revenue").click()
    page.get_by_placeholder("Enter explanation for revenue").fill("Some explanation for testing")
    page.get_by_role("button", name="Save").click()
    page.get_by_role("button", name="Generate Voucher").click()
    page.get_by_label("Diesel", exact=True).click()
    page.get_by_label("Diesel", exact=True).fill("10")
    page.get_by_label("Diesel", exact=True).press("Tab")
    page.get_by_label("Diesel Litres").fill("10")
    page.get_by_label("Diesel Litres").press("Tab")
    page.get_by_label("Coil Technician").press("Tab")
    page.get_by_label("Toll").press("Tab")
    page.get_by_label("Cleaning").fill("10")
    page.get_by_label("Cleaning").press("Tab")
    page.get_by_label("Alliedmor").press("Tab")
    page.get_by_label("City Parchi").press("Tab")
    page.get_by_label("Refreshment").press("Tab")
    page.get_by_label("Repair").fill("10")
    page.get_by_label("Repair").press("Tab")
    page.get_by_label("Challan").fill("10")
    page.get_by_label("Challan").press("Tab")
    page.get_by_label("Miscellaneous Expense").fill("10")
    page.get_by_label("Miscellaneous Expense").press("Tab")
    page.get_by_label("Explanation").fill("Some explanation")
    expect(page.locator("form")).to_contain_text("12,720")
    expect(page.locator("form")).to_contain_text("8,395")
    expect(page.locator("form")).to_contain_text("-4,325")
    with page.expect_popup() as page1_info:
        page.get_by_role("button", name="Submit").click()
    page1 = page1_info.value
    page1.close()


def test_conductor_id_missing(page: Page):
    page.goto("http://localhost:3000/dashboard/employee")
    page.get_by_role("link", name="Add Closing Vouchers").click()
    page.get_by_text("Select Route").click()
    page.get_by_role("option", name="Faisalabad (New Subhan) - Lahore (Skyways-Lahore)").click()
    page.get_by_text("Select Bus Number").click()
    page.get_by_role("option", name="1658").click()
    page.locator("button").filter(has_text="Select Driver").click()
    page.get_by_role("option", name="Muhammad Imtiaz").click()
    page.get_by_placeholder("Enter Voucher Number").click()
    page.get_by_placeholder("Enter Voucher Number").fill("1234")
    page.get_by_role("button", name="Add Trip").click()
    page.get_by_role("combobox").click()
    page.get_by_role("option", name="Faisalabad (New Subhan) - Lahore (Skyways-Lahore)").click()
    page.get_by_label("Full Ticket Count").click()
    page.get_by_label("Full Ticket Count").fill("10")
    page.get_by_label("Full Ticket Count").press("Tab")
    page.get_by_placeholder("Enter half ticket count").fill("3")
    page.get_by_placeholder("Enter half ticket count").press("Tab")
    page.get_by_placeholder("Enter free ticket count").fill("2")
    page.get_by_placeholder("Enter free ticket count").press("Tab")
    page.get_by_placeholder("Enter load expense").fill("100")
    page.get_by_placeholder("Enter load expense").press("Tab")
    page.get_by_label("Reward Commission").fill("100")
    page.get_by_label("Reward Commission").press("Tab")
    page.get_by_label("Refreshment Expense").fill("100")
    page.get_by_label("Refreshment Expense").press("Tab")
    page.get_by_placeholder("Enter miscellaneous amount").fill("100")
    page.get_by_placeholder("Enter miscellaneous amount").press("Tab")
    page.get_by_placeholder("Enter checker expenses").fill("100")
    expect(page.get_by_placeholder("Actual revenue")).to_have_value("8395");
    page.get_by_placeholder("Enter explanation for revenue").click()
    page.get_by_placeholder("Enter explanation for revenue").fill("Some explanation for testing")
    page.get_by_role("button", name="Save").click()
    page.get_by_role("button", name="Generate Voucher").click()
    page.get_by_label("Diesel", exact=True).click()
    page.get_by_label("Diesel", exact=True).fill("10")
    page.get_by_label("Diesel", exact=True).press("Tab")
    page.get_by_label("Diesel Litres").fill("10")
    page.get_by_label("Diesel Litres").press("Tab")
    page.get_by_label("Coil Technician").press("Tab")
    page.get_by_label("Toll").press("Tab")
    page.get_by_label("Cleaning").fill("10")
    page.get_by_label("Cleaning").press("Tab")
    page.get_by_label("Alliedmor").press("Tab")
    page.get_by_label("City Parchi").press("Tab")
    page.get_by_label("Refreshment").press("Tab")
    page.get_by_label("Repair").fill("10")
    page.get_by_label("Repair").press("Tab")
    page.get_by_label("Challan").fill("10")
    page.get_by_label("Challan").press("Tab")
    page.get_by_label("Miscellaneous Expense").fill("10")
    page.get_by_label("Miscellaneous Expense").press("Tab")
    page.get_by_label("Explanation").fill("Some explanation")
    expect(page.locator("form")).to_contain_text("12,720")
    expect(page.locator("form")).to_contain_text("8,395")
    expect(page.locator("form")).to_contain_text("-4,325")
    with page.expect_popup() as page1_info:
        page.get_by_role("button", name="Submit").click()
    page1 = page1_info.value
    page1.close()
